version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    hostname: iris
    ports: 
      - 1972:1972
      - 52773:52773
      - 53773
    #environment: 
      #ISC_DATA_DIRECTORY: /external/conf
    volumes:
      - ./:/irisdev/app
      - ./share/:/tmp/share
      #- fhiraas_external:/external
  proxy:
    build:
      context: https/.
      args:
        link: 'iris'
        port: '52773'
    image: proxyiris:latest
    ports:
    - "443:443"

volumes:
  fhiraas_external: {}